/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseTable: typeof import('./src/components/base/BaseTable.vue')['default']
    BaseTreeSelect: typeof import('./src/components/base/BaseTreeSelect.vue')['default']
    Companies: typeof import('./src/components/common/companies/Companies.vue')['default']
    CompanyModal: typeof import('./src/components/common/companies/CompanyModal.vue')['default']
    EmployeeModal: typeof import('./src/components/common/employees/EmployeeModal.vue')['default']
    Employees: typeof import('./src/components/common/employees/Employees.vue')['default']
    GasStationModal: typeof import('./src/components/common/gas-stations/GasStationModal.vue')['default']
    GasStations: typeof import('./src/components/common/gas-stations/GasStations.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTreeSelect: typeof import('naive-ui')['NTreeSelect']
    Regions: typeof import('./src/components/common/regions/Regions.vue')['default']
    RegionsModal: typeof import('./src/components/common/regions/RegionsModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tickets: typeof import('./src/components/common/Tickets.vue')['default']
    WarehouseModal: typeof import('./src/components/common/warehouses/WarehouseModal.vue')['default']
    Warehouses: typeof import('./src/components/common/warehouses/Warehouses.vue')['default']
  }
}
